/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TPV_Moviles.Modulos.Login.Vista;

/**
 *
 * @author Raul
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        etiTitulo = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        labelUsuario = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        btnAcceder = new javax.swing.JButton();
        Registrar = new javax.swing.JLabel();
        Recordar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.orange));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        etiTitulo.setForeground(java.awt.Color.green);
        etiTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiTitulo.setText("Login de empleados");
        jLayeredPane1.add(etiTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 27, 289, 28));

        txtUsuario.setBorder(null);
        jLayeredPane1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 171, 210, -1));

        txtPassword.setBorder(null);
        jLayeredPane1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 210, -1));

        labelUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelUsuario.setForeground(java.awt.Color.orange);
        labelUsuario.setText("DNI:");
        jLayeredPane1.add(labelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        labelPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelPassword.setForeground(java.awt.Color.orange);
        labelPassword.setText("Password:");
        jLayeredPane1.add(labelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        btnAcceder.setText("Acceder");
        btnAcceder.setOpaque(false);
        jLayeredPane1.add(btnAcceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, -1));

        Registrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Registrar.setForeground(java.awt.Color.white);
        Registrar.setText("¿Todavía no te has registrado?");
        jLayeredPane1.add(Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 198, -1));

        Recordar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Recordar.setForeground(java.awt.Color.white);
        Recordar.setText("¿Olvidaste tu contraseña?");
        jLayeredPane1.add(Recordar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 173, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TPV/Img/default-avatar.png"))); // NOI18N
        jLayeredPane1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 73, -1, 61));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TPV/Img/fondo5.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Recordar;
    public static javax.swing.JLabel Registrar;
    public static javax.swing.JButton btnAcceder;
    private javax.swing.JLabel etiTitulo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelUsuario;
    public static javax.swing.JPasswordField txtPassword;
    public static javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
