/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TPV_Moviles.Modulos.Inicio.Vista;

/**
 *
 * @author Raul
 */
public class Ventana_Empleados extends javax.swing.JFrame {

    /**
     * Creates new form Panel
     */
    public Ventana_Empleados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuConsEmp = new javax.swing.JMenu();
        jMenuEF = new javax.swing.JMenu();
        MenuPager = new javax.swing.JMenuItem();
        MenuConf = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        aparienciaMetal = new javax.swing.JMenuItem();
        aparienciaGTK = new javax.swing.JMenuItem();
        aparienciaNimbus = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Euro = new javax.swing.JMenuItem();
        Libra = new javax.swing.JMenuItem();
        Dolar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        fecha4 = new javax.swing.JMenuItem();
        fecha5 = new javax.swing.JMenuItem();
        fecha6 = new javax.swing.JMenuItem();
        fecha1 = new javax.swing.JMenuItem();
        fecha2 = new javax.swing.JMenuItem();
        fecha3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        decimal1 = new javax.swing.JMenuItem();
        decimal2 = new javax.swing.JMenuItem();
        decimal3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TPV_Moviles/Img/LogoInicio.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 350, 120));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TPV_Moviles/Img/portada.jpg"))); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, 410));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TPV_Moviles/Img/fondo1.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 630));

        MenuConsEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TPV/Img/editpaste.png"))); // NOI18N
        MenuConsEmp.setText("Administracion");

        jMenuEF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TPV/Img/user-inv.png"))); // NOI18N
        jMenuEF.setText("Clientes");

        MenuPager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TPV/Img/ButtonTables.png"))); // NOI18N
        MenuPager.setText("Gestion_Pager");
        jMenuEF.add(MenuPager);

        MenuConsEmp.add(jMenuEF);

        jMenuBar1.add(MenuConsEmp);

        MenuConf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TPV/Img/configure.png"))); // NOI18N
        MenuConf.setText("Configuración");

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TPV/Img/colorize.png"))); // NOI18N
        jMenu1.setText("Apariencia");

        aparienciaMetal.setText("Metal");
        jMenu1.add(aparienciaMetal);

        aparienciaGTK.setText("GTK Windows");
        jMenu1.add(aparienciaGTK);

        aparienciaNimbus.setText("Nimbus");
        jMenu1.add(aparienciaNimbus);

        MenuConf.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TPV/Img/moneda.png"))); // NOI18N
        jMenu2.setText("Moneda");

        Euro.setText("Euro €");
        jMenu2.add(Euro);

        Libra.setText("Libra £");
        jMenu2.add(Libra);

        Dolar.setText("Dolar $");
        jMenu2.add(Dolar);

        MenuConf.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TPV/Img/fecha.png"))); // NOI18N
        jMenu3.setText("Fecha");

        fecha4.setText("dd-mm-yyyy");
        jMenu3.add(fecha4);

        fecha5.setText("mm-dd-yyyy");
        jMenu3.add(fecha5);

        fecha6.setText("yyyy-mm-dd");
        jMenu3.add(fecha6);

        fecha1.setText("dd/mm/yyyy");
        jMenu3.add(fecha1);

        fecha2.setText("mm/dd/yyyy");
        jMenu3.add(fecha2);

        fecha3.setText("yyyy/mm/dd");
        jMenu3.add(fecha3);

        MenuConf.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TPV/Img/decimales.png"))); // NOI18N
        jMenu4.setText("Decimales");

        decimal1.setText("1 Decimal");
        jMenu4.add(decimal1);

        decimal2.setText("2 Decimales");
        jMenu4.add(decimal2);

        decimal3.setText("3 Decimales");
        jMenu4.add(decimal3);

        MenuConf.add(jMenu4);

        jMenuBar1.add(MenuConf);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JMenuItem Dolar;
    public static javax.swing.JMenuItem Euro;
    public static javax.swing.JMenuItem Libra;
    public static javax.swing.JMenu MenuConf;
    private javax.swing.JMenu MenuConsEmp;
    public static javax.swing.JMenuItem MenuPager;
    public static javax.swing.JMenuItem aparienciaGTK;
    public static javax.swing.JMenuItem aparienciaMetal;
    public static javax.swing.JMenuItem aparienciaNimbus;
    public static javax.swing.JMenuItem decimal1;
    public static javax.swing.JMenuItem decimal2;
    public static javax.swing.JMenuItem decimal3;
    public static javax.swing.JMenuItem fecha1;
    public static javax.swing.JMenuItem fecha2;
    public static javax.swing.JMenuItem fecha3;
    public static javax.swing.JMenuItem fecha4;
    public static javax.swing.JMenuItem fecha5;
    public static javax.swing.JMenuItem fecha6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JMenu jMenuEF;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
