/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TPV_Moviles.Modulos.GestionProductos.Vista;


/**
 *
 * @author Raul
 */
public class RegistroPro extends javax.swing.JFrame {

    /**
     * Creates new form RegistroClie
     */
    public RegistroPro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        iconoalta = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labRef = new javax.swing.JLabel();
        labModelo = new javax.swing.JLabel();
        labDesc = new javax.swing.JLabel();
        txtReferencia = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtDesc = new javax.swing.JTextField();
        btnAnyadir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnIrPager = new javax.swing.JButton();
        labTipoP = new javax.swing.JLabel();
        cmbTipoP = new javax.swing.JComboBox();
        labFmercado = new javax.swing.JLabel();
        labMarca = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        dcFmercado = new com.toedter.calendar.JDateChooser();
        NoRef = new javax.swing.JLabel();
        NoModelo = new javax.swing.JLabel();
        NoMarca = new javax.swing.JLabel();
        NoDesc = new javax.swing.JLabel();
        NoFmercado = new javax.swing.JLabel();
        labelFotoUsu = new javax.swing.JLabel();
        labelNomUsu = new javax.swing.JLabel();
        etiTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        iconoalta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TPV_Moviles/Img/movilalta.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labRef.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        labRef.setForeground(java.awt.Color.orange);
        labRef.setText("Referencia:");
        jPanel1.add(labRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 37, -1, -1));

        labModelo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        labModelo.setForeground(java.awt.Color.orange);
        labModelo.setText("Modelo:");
        jPanel1.add(labModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 89, -1, -1));

        labDesc.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        labDesc.setForeground(java.awt.Color.orange);
        labDesc.setText("Descripcion:");
        jPanel1.add(labDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 198, 90, -1));
        jPanel1.add(txtReferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 36, 170, -1));
        jPanel1.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 88, 170, -1));
        jPanel1.add(txtDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 182, 161, 50));

        btnAnyadir.setText("Añadir");
        btnAnyadir.setOpaque(false);
        jPanel1.add(btnAnyadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, -1, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.setOpaque(false);
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, -1, -1));

        btnIrPager.setText("Ir Pager");
        btnIrPager.setOpaque(false);
        jPanel1.add(btnIrPager, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, -1, -1));

        labTipoP.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        labTipoP.setForeground(java.awt.Color.orange);
        labTipoP.setText("Tipo Producto:");
        jPanel1.add(labTipoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        cmbTipoP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Smartphone", "Accesorio" }));
        jPanel1.add(cmbTipoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 161, -1));

        labFmercado.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        labFmercado.setForeground(java.awt.Color.orange);
        labFmercado.setText("Fecha Mercado:");
        jPanel1.add(labFmercado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 282, -1, -1));

        labMarca.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        labMarca.setForeground(java.awt.Color.orange);
        labMarca.setText("Marca:");
        jPanel1.add(labMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 137, -1, -1));
        jPanel1.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 136, 160, -1));

        dcFmercado.setDateFormatString("dd-MM-yyyy");
        jPanel1.add(dcFmercado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 160, -1));

        NoRef.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TPV_Moviles/Img/cancel.png"))); // NOI18N
        jPanel1.add(NoRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 20, 20));

        NoModelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TPV_Moviles/Img/cancel.png"))); // NOI18N
        jPanel1.add(NoModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 20, 20));

        NoMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TPV_Moviles/Img/cancel.png"))); // NOI18N
        jPanel1.add(NoMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 20, 20));

        NoDesc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TPV_Moviles/Img/cancel.png"))); // NOI18N
        jPanel1.add(NoDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 20, 20));

        NoFmercado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TPV_Moviles/Img/cancel.png"))); // NOI18N
        jPanel1.add(NoFmercado, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 20, 20));

        labelFotoUsu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelFotoUsu.setOpaque(true);

        labelNomUsu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNomUsu.setForeground(java.awt.Color.blue);
        labelNomUsu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        etiTitulo.setFont(new java.awt.Font("Verdana", 1, 21)); // NOI18N
        etiTitulo.setForeground(java.awt.Color.green);
        etiTitulo.setText("Registrar Nuevo Producto");

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(etiTitulo))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iconoalta, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(labelNomUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelFotoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addComponent(etiTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFotoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNomUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconoalta, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
        );
        jLayeredPane2.setLayer(iconoalta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(labelFotoUsu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(labelNomUsu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(etiTitulo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel NoDesc;
    public static javax.swing.JLabel NoFmercado;
    public static javax.swing.JLabel NoMarca;
    public static javax.swing.JLabel NoModelo;
    public static javax.swing.JLabel NoRef;
    public static javax.swing.JButton btnAnyadir;
    public static javax.swing.JButton btnCancelar;
    public static javax.swing.JButton btnIrPager;
    public static javax.swing.JComboBox cmbTipoP;
    public static com.toedter.calendar.JDateChooser dcFmercado;
    private javax.swing.JLabel etiTitulo;
    private javax.swing.JLabel iconoalta;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labDesc;
    private javax.swing.JLabel labFmercado;
    private javax.swing.JLabel labMarca;
    private javax.swing.JLabel labModelo;
    private javax.swing.JLabel labRef;
    private javax.swing.JLabel labTipoP;
    public static javax.swing.JLabel labelFotoUsu;
    public static javax.swing.JLabel labelNomUsu;
    public static javax.swing.JTextField txtDesc;
    public static javax.swing.JTextField txtMarca;
    public static javax.swing.JTextField txtModelo;
    public static javax.swing.JTextField txtReferencia;
    // End of variables declaration//GEN-END:variables
}
