/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TPV_Moviles.Modulos.GestionClientes.GestionCli.Vista;

/**
 *
 * @author Raul
 */
public class AltaEF extends javax.swing.JFrame {

    /**
     * Creates new form RegistroClie
     */
    public AltaEF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        iconoalta = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        etiNombre = new javax.swing.JLabel();
        etiApellidos = new javax.swing.JLabel();
        etiDNI = new javax.swing.JLabel();
        etiTelefono = new javax.swing.JLabel();
        etifechanac = new javax.swing.JLabel();
        etifechaalta = new javax.swing.JLabel();
        etiEmail = new javax.swing.JLabel();
        etiTipo = new javax.swing.JLabel();
        etiEdad = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        dcfnac = new com.toedter.calendar.JDateChooser();
        txtAntiguedad = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        cmbTipo = new javax.swing.JComboBox();
        btnAnyadir = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        NoNombre = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        dcFAlta = new com.toedter.calendar.JDateChooser();
        etiAntiguedad = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        NoApellidos = new javax.swing.JLabel();
        NoDNI = new javax.swing.JLabel();
        NoTelefono = new javax.swing.JLabel();
        NOFNAC = new javax.swing.JLabel();
        NOFALTA = new javax.swing.JLabel();
        NoEmail = new javax.swing.JLabel();
        labelFotoUsu = new javax.swing.JLabel();
        labelNomUsu = new javax.swing.JLabel();
        etiTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane2.setPreferredSize(new java.awt.Dimension(1100, 509));

        iconoalta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TPV_Moviles/Img/cliente.jpg"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiNombre.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        etiNombre.setForeground(java.awt.Color.orange);
        etiNombre.setText("Nombre:");
        jPanel1.add(etiNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 30, -1, -1));

        etiApellidos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        etiApellidos.setForeground(java.awt.Color.orange);
        etiApellidos.setText("Apellidos:");
        jPanel1.add(etiApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 72, -1, -1));

        etiDNI.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        etiDNI.setForeground(java.awt.Color.orange);
        etiDNI.setText("DNI:");
        jPanel1.add(etiDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 114, -1, -1));

        etiTelefono.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        etiTelefono.setForeground(java.awt.Color.orange);
        etiTelefono.setText("Telefono:");
        jPanel1.add(etiTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 156, -1, -1));

        etifechanac.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        etifechanac.setForeground(java.awt.Color.orange);
        etifechanac.setText("Fecha Nacimiento:");
        jPanel1.add(etifechanac, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 198, -1, -1));

        etifechaalta.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        etifechaalta.setForeground(java.awt.Color.orange);
        etifechaalta.setText("Fecha Alta:");
        jPanel1.add(etifechaalta, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 241, -1, -1));

        etiEmail.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        etiEmail.setForeground(java.awt.Color.orange);
        etiEmail.setText("Email:");
        jPanel1.add(etiEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        etiTipo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        etiTipo.setForeground(java.awt.Color.orange);
        etiTipo.setText("Tipo Usuario:");
        jPanel1.add(etiTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        etiEdad.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        etiEdad.setForeground(java.awt.Color.orange);
        etiEdad.setText("Edad:");
        jPanel1.add(etiEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 283, -1, -1));
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 155, 161, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 29, 161, -1));
        jPanel1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 71, 161, -1));
        jPanel1.add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 113, 161, -1));
        jPanel1.add(dcfnac, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 198, 161, -1));

        txtAntiguedad.setEditable(false);
        jPanel1.add(txtAntiguedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 31, -1));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 161, -1));

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cliente", "Administrador", " " }));
        jPanel1.add(cmbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 123, -1));

        btnAnyadir.setText("Dar de alta");
        btnAnyadir.setOpaque(false);
        jPanel1.add(btnAnyadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 448, -1, -1));

        btnLimpiar.setText("Cancelar");
        btnLimpiar.setOpaque(false);
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 448, -1, -1));

        NoNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TPV_Moviles/Img/cancel.png"))); // NOI18N
        jPanel1.add(NoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 29, -1, 20));

        btnVolver.setText("Ir Pager");
        btnVolver.setOpaque(false);
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 448, -1, -1));
        jPanel1.add(dcFAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 244, 161, -1));

        etiAntiguedad.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        etiAntiguedad.setForeground(java.awt.Color.orange);
        etiAntiguedad.setText("Antiguedad:");
        jPanel1.add(etiAntiguedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        txtEdad.setEditable(false);
        jPanel1.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 282, 31, -1));

        NoApellidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TPV_Moviles/Img/cancel.png"))); // NOI18N
        jPanel1.add(NoApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 71, -1, 20));

        NoDNI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TPV_Moviles/Img/cancel.png"))); // NOI18N
        jPanel1.add(NoDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 113, -1, 20));

        NoTelefono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TPV_Moviles/Img/cancel.png"))); // NOI18N
        jPanel1.add(NoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 155, -1, 20));

        NOFNAC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TPV_Moviles/Img/cancel.png"))); // NOI18N
        jPanel1.add(NOFNAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 198, -1, 20));

        NOFALTA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TPV_Moviles/Img/cancel.png"))); // NOI18N
        jPanel1.add(NOFALTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 244, -1, 20));

        NoEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TPV_Moviles/Img/cancel.png"))); // NOI18N
        jPanel1.add(NoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, -1, 20));

        labelFotoUsu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelFotoUsu.setOpaque(true);

        labelNomUsu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNomUsu.setForeground(java.awt.Color.orange);
        labelNomUsu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        etiTitulo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        etiTitulo.setForeground(java.awt.Color.green);
        etiTitulo.setText("Alta Empleado Fijo");

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiTitulo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(labelNomUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelFotoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(iconoalta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelFotoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(labelNomUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(62, 62, 62)
                        .addComponent(etiTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(iconoalta, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))))
        );
        jLayeredPane2.setLayer(iconoalta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(labelFotoUsu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(labelNomUsu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(etiTitulo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel NOFALTA;
    public static javax.swing.JLabel NOFNAC;
    public static javax.swing.JLabel NoApellidos;
    public static javax.swing.JLabel NoDNI;
    public static javax.swing.JLabel NoEmail;
    public static javax.swing.JLabel NoNombre;
    public static javax.swing.JLabel NoTelefono;
    public static javax.swing.JButton btnAnyadir;
    public static javax.swing.JButton btnLimpiar;
    public static javax.swing.JButton btnVolver;
    public static javax.swing.JComboBox cmbTipo;
    public static com.toedter.calendar.JDateChooser dcFAlta;
    public static com.toedter.calendar.JDateChooser dcfnac;
    private javax.swing.JLabel etiAntiguedad;
    private javax.swing.JLabel etiApellidos;
    private javax.swing.JLabel etiDNI;
    private javax.swing.JLabel etiEdad;
    private javax.swing.JLabel etiEmail;
    private javax.swing.JLabel etiNombre;
    private javax.swing.JLabel etiTelefono;
    public static javax.swing.JLabel etiTipo;
    private javax.swing.JLabel etiTitulo;
    private javax.swing.JLabel etifechaalta;
    private javax.swing.JLabel etifechanac;
    private javax.swing.JLabel iconoalta;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel2;
    public static javax.swing.JLabel labelFotoUsu;
    public static javax.swing.JLabel labelNomUsu;
    public static javax.swing.JTextField txtAntiguedad;
    public static javax.swing.JTextField txtApellidos;
    public static javax.swing.JTextField txtDNI;
    public static javax.swing.JTextField txtEdad;
    public static javax.swing.JTextField txtEmail;
    public static javax.swing.JTextField txtNombre;
    public static javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
